name: CI
on: [push]
jobs:

  build-cares:
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
    - name: env/setup
      run: env/setup.sh
    - name: git submodule
      run: env/submodule.sh --jobs 3

    - name: make Android .apk
      run: make -j3 -C app-android precache='--no-ios' out-and/armeabi-v7a/./vpn/shared/wsk/c-ares/Makefile
